import React from 'react';




import { TiUserAddOutline } from "react-icons/ti"; // add services
import { IoCart } from "react-icons/io5"; // total car
import { MdOutlineLocalCarWash } from "react-icons/md"; //pending
<link href="https://cdn.jsdelivr.net/npm/flowbite@3.1.2/dist/flowbite.min.css" rel="stylesheet" />
import { FaCar } from "react-icons/fa";

const Dashboard = () => {
	
	return (
		
		<div >
			<p className='font-semibold text-4xl text-red-700  '>Dashboard</p>



			{/*  HEADING START */}
			<div className='flex space-x-3.5 pt-5 px-1 shadow-2xl  ' >
				<div >
					<div className='border-2   bg-white text-red-700 w-64 h-21 text-center  
					      hover:scale-105 shadow-xl rounded-2xl '>Active Services
						  {/* GRAPH START */}


						<div className="max-w-sm w-full bg-white rounded-lg shadow-sm dark:bg-gray-800 p-4 md:p-6">

							<div className="flex justify-between mb-3">
								<div className="flex justify-center items-center">
									<h5 className="text-xl font-bold leading-none text-gray-900 dark:text-white pe-1">Website traffic</h5>
									<svg data-popover-target="chart-info" data-popover-placement="bottom" className="w-3.5 h-3.5 text-gray-500 dark:text-gray-400 hover:text-gray-900 dark:hover:text-white cursor-pointer ms-1" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
										<path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5Zm0 16a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3Zm1-5.034V12a1 1 0 0 1-2 0v-1.418a1 1 0 0 1 1.038-.999 1.436 1.436 0 0 0 1.488-1.441 1.501 1.501 0 1 0-3-.116.986.986 0 0 1-1.037.961 1 1 0 0 1-.96-1.037A3.5 3.5 0 1 1 11 11.466Z" />
									</svg>
									<div data-popover id="chart-info" role="tooltip" className="absolute z-10 invisible inline-block text-sm text-gray-500 transition-opacity duration-300 bg-white border border-gray-200 rounded-lg shadow-xs opacity-0 w-72 dark:bg-gray-800 dark:border-gray-600 dark:text-gray-400">
										<div className="p-3 space-y-2">
											<h3 className="font-semibold text-gray-900 dark:text-white">Activity growth - Incremental</h3>
											<p>Report helps navigate cumulative growth of community activities. Ideally, the chart should have a growing trend, as stagnating chart signifies a significant decrease of community activity.</p>
											<h3 className="font-semibold text-gray-900 dark:text-white">Calculation</h3>
											<p>For each date bucket, the all-time volume of activities is calculated. This means that activities in period n contain all activities up to period n, plus the activities generated by your community in period.</p>
											<a href="#" className="flex items-center font-medium text-blue-600 dark:text-blue-500 dark:hover:text-blue-600 hover:text-blue-700 hover:underline">Read more <svg className="w-2 h-2 ms-1.5 rtl:rotate-180" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
												<path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 9 4-4-4-4" />
											</svg></a>
										</div>
										<div data-popper-arrow></div>
									</div>
								</div>
								<div>
									<button type="button" data-tooltip-target="data-tooltip" data-tooltip-placement="bottom" class="hidden sm:inline-flex items-center justify-center text-gray-500 w-8 h-8 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-700 focus:outline-none focus:ring-4 focus:ring-gray-200 dark:focus:ring-gray-700 rounded-lg text-sm"><svg class="w-3.5 h-3.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 16 18">
										<path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 1v11m0 0 4-4m-4 4L4 8m11 4v3a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2v-3" />
									</svg><span className="sr-only">Download data</span>
									</button>
									<div id="data-tooltip" role="tooltip" className="absolute z-10 invisible inline-block px-3 py-2 text-sm font-medium text-white transition-opacity duration-300 bg-gray-900 rounded-lg shadow-xs opacity-0 tooltip dark:bg-gray-700">
										Download CSV
										<div className="tooltip-arrow" data-popper-arrow></div>
									</div>
								</div>
							</div>

							<div>
								<div className="flex" id="devices">
									
								</div>
							</div>

							
							<div className="py-6" id="donut-chart"></div>

							<div className="grid grid-cols-1 items-center border-gray-200 border-t dark:border-gray-700 justify-between">
								<div className="flex justify-between items-center pt-5">
									
									<button
										id="dropdownDefaultButton"
										data-dropdown-toggle="lastDaysdropdown"
										data-dropdown-placement="bottom"
										className="text-sm font-medium text-gray-500 dark:text-gray-400 hover:text-gray-900 text-center inline-flex items-center dark:hover:text-white"
										type="button">
										Last 7 days
										<svg className="w-2.5 m-2.5 ms-1.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 10 6">
											<path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 4 4 4-4" />
										</svg>
									</button>
									<div id="lastDaysdropdown" className="z-10 hidden bg-white divide-y divide-gray-100 rounded-lg shadow-sm w-44 dark:bg-gray-700">
										<ul className="py-2 text-sm text-gray-700 dark:text-gray-200" aria-labelledby="dropdownDefaultButton">
											<li>
												<a href="#" className="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Yesterday</a>
											</li>
											<li>
												<a href="#" className="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Today</a>
											</li>
											<li>
												<a href="#" className="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Last 7 days</a>
											</li>
											<li>
												<a href="#" className="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Last 30 days</a>
											</li>
											<li>
												<a href="#" className="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Last 90 days</a>
											</li>
										</ul>
									</div>
									<a
										href="#"
										className="uppercase text-sm font-semibold inline-flex items-center rounded-lg text-blue-600 hover:text-blue-700 dark:hover:text-blue-500  hover:bg-gray-100 dark:hover:bg-gray-700 dark:focus:ring-gray-700 dark:border-gray-700 px-3 py-2">
										Traffic analysis
										<svg className="w-2.5 h-2.5 ms-1.5 rtl:rotate-180" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
											<path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 9 4-4-4-4" />
										</svg>
									</a>
								</div>
							</div>
						</div>


						  {/* GRAPH END */}
						  
						  
						   </div>
				</div>
				<div>
					<div className='border  bg-white text-red-700  w-64 h-20 text-center rounded-2xl hover:scale-105 shadow-xl'>Pending Services</div>
				</div>
				<div>
					<div className='border  bg-white text-red-700  w-64 h-20 text-center rounded-2xl hover:scale-105 shadow-xl'>Completed Services</div>
				</div>
				<div>
					<div className='border bg-white   text-red-700  w-64 h-20  text-center rounded-2xl hover:scale-105 shadow-xl'>Overall Services</div>
				</div>
				
			</div>
			{/*  HEADING END */}


			<div >
				<div className="relative overflow-x-auto shadow-5xl sm:rounded-lg  ">
					<table className="w-8/1  text-left rtl:text-right
				 text-red-400  rounded-lg  my-4 ">


						<thead className="text-sm text-red-700 uppercase 
						  bg-white ">
							<tr >
								<th scope="col" className="px-6 py-3 hover:bg-red-900  hover:text-white ">
									Customer
								</th>
								<th scope="col" className="px-6 py-3 hover:bg-red-900 hover:text-white ">
									Location
								</th>
								<th scope="col" className="px-6 py-3 hover:bg-red-900 hover:text-white ">
									Service Details
								</th>
								<th scope="col" className="px-6 py-3 hover:bg-red-900 hover:text-white ">
									Service cost
								</th>
								<th scope="col" className="px-6 py-3 hover:bg-red-900 hover:text-white">
									Service Status
								</th>
							</tr>
						</thead>
						<tbody>
							<tr className="odd:bg-white odd:dark:bg-gray-900 even:bg-gray-50 even:dark:bg-gray-800 border-b dark:border-gray-700
							 border-gray-200 hover:bg-red-100   hover:scale-95 shadow-2xl ">
								<th scope="row" className="px-6 py-4 font-medium text-red-700 whitespace-nowrap dark:text-white  ">
									varun
								</th>
								<td className="px-6 py-4 ">
									chennai
								</td>
								<td className="px-6 py-4 text-sm">
									<p className='text-left'>order id #656755</p>
									<div className='flex flex-row gap-x-3 '>
										<div>
											<FaCar className='text-left w-6 h-6' />
										</div>
										<div className='text-center'>
											<p >Body dent </p>
											<p >1.5k</p>
										</div>
										 
									</div>	
									
								</td>
								<td className="px-6 py-4">
									$2999
								</td>
								<td className="px-6 py-4">
									<button type="button" className="text-white bg-gradient-to-r from-red-600 via-red-500
									 to-red-600 hover:bg-gradient-to-br focus:ring-4 focus:outline-none
									  focus:ring-red-300 dark:focus:ring-red-800 shadow-lg shadow-red-500/50 dark:shadow-lg 
									  dark:shadow-red-800/80 font-medium rounded-lg text-sm px-0.5 py-1 text-center me-2 mb-2">VIEW</button>
								
								</td>
							</tr>
							<tr className="odd:bg-white odd:dark:bg-gray-900 even:bg-gray-50 even:dark:bg-gray-800 border-b
							 dark:border-gray-700 border-gray-200 hover:bg-red-100 hover:scale-95 shadow-2xl">
								<th scope="row" className="px-6 py-4 font-medium text-red-700 whitespace-nowrap dark:text-white">
									lokesh
								</th>
								<td className="px-6 py-4">
									coimbatore
								</td>
								<td className="px-6 py-4 text-sm">
									<p className='text-left'>order id #656755</p>
									<div className='flex flex-row gap-x-3 '>
										<div>
											<FaCar className='text-left w-6 h-6' />
										</div>
										<div className='text-center'>
											<p >Body dent </p>
											<p >1.5k</p>
										</div>

									</div>

								</td>
								<td className="px-6 py-4">
									$1999
								</td>
								<td className="px-6 py-4">
									<button type="button" className="text-white bg-gradient-to-r from-red-600 via-red-500
									 to-red-600 hover:bg-gradient-to-br focus:ring-4 focus:outline-none
									  focus:ring-red-300 dark:focus:ring-red-800 shadow-lg shadow-red-500/50 dark:shadow-lg 
									  dark:shadow-red-800/80 font-medium rounded-lg text-sm px-0.5 py-1 text-center me-2 mb-2">VIEW</button>

								</td>
							</tr>
							<tr className="odd:bg-white odd:dark:bg-gray-900 even:bg-gray-50 even:dark:bg-gray-800 border-b
							 dark:border-gray-700 border-gray-200 hover:bg-red-100 hover:scale-95 shadow-2xl">
								<th scope="row" className="px-6 py-4 font-medium text-red-700 whitespace-nowrap dark:text-white">
									Magic Mouse 2
								</th>
								<td className="px-6 py-4">
									bangalore
								</td>
								<td className="px-6 py-4 text-sm">
									<p className='text-left'>order id #656755</p>
									<div className='flex flex-row gap-x-3 '>
										<div>
											<FaCar className='text-left w-6 h-6' />
										</div>
										<div className='text-center'>
											<p >Body dent </p>
											<p >1.5k</p>
										</div>

									</div>

								</td>
								<td className="px-6 py-4">
									$99
								</td>
								<td className="px-6 py-4">
									<button type="button" className="text-white bg-gradient-to-r from-red-600 via-red-500
									 to-red-600 hover:bg-gradient-to-br focus:ring-4 focus:outline-none
									  focus:ring-red-300 dark:focus:ring-red-800 shadow-lg shadow-red-500/50 dark:shadow-lg 
									  dark:shadow-red-800/80 font-medium rounded-lg text-sm px-0.5 py-1 text-center me-2 mb-2">VIEW</button>

								</td>
							</tr>
							<tr className="odd:bg-white odd:dark:bg-gray-900 even:bg-gray-50 even:dark:bg-gray-800 border-b
							 dark:border-gray-700 border-gray-200 hover:bg-red-100 hover:scale-95 shadow-2xl">
								<th scope="row" className="px-6 py-4 font-medium text-red-700 whitespace-nowrap dark:text-white">
									Apple Watch 5
								</th>
								<td className="px-6 py-4">
									coimbatore
								</td>
								<td className="px-6 py-4 text-sm">
									<p className='text-left'>order id #656755</p>
									<div className='flex flex-row gap-x-3 '>
										<div>
											<FaCar className='text-left w-6 h-6' />
										</div>
										<div className='text-center'>
											<p >Body dent </p>
											<p >1.5k</p>
										</div>

									</div>

								</td>
								<td className="px-6 py-4">
									$999
								</td>
								<td className="px-6 py-4">

									<button type="button" className="text-white bg-gradient-to-r from-red-600 via-red-500
									 to-red-600 hover:bg-gradient-to-br focus:ring-4 focus:outline-none
									  focus:ring-red-300 dark:focus:ring-red-800 shadow-lg shadow-red-500/50 dark:shadow-lg 
									  dark:shadow-red-800/80 font-medium rounded-lg text-sm px-0.5 py-1 text-center me-2 mb-2">VIEW</button>
									</td>
							</tr>

							<tr className="odd:bg-white odd:dark:bg-gray-900 even:bg-gray-50 even:dark:bg-gray-800 border-b
							 hover:scale-95 shadow-2xl dark:border-gray-700 border-gray-200 hover:bg-red-100">
								<th scope="row" className="px-6 py-4 font-medium text-red-700 whitespace-nowrap dark:text-white">
									Google Pixel Phone
								</th>
								<td className="px-6 py-4">
									pondycherry
								</td>
								<td className="px-6 py-4 text-sm">
									<p className='text-left'>order id #656755</p>
									<div className='flex flex-row gap-x-3 '>
										<div>
											<FaCar className='text-left w-6 h-6' />
										</div>
										<div className='text-center'>
											<p >Body dent </p>
											<p >1.5k</p>
										</div>

									</div>

								</td>
								<td className="px-6 py-4">
									$799
								</td>
								<td className="px-6 py-4">
								
									<button type="button" className="text-white bg-gradient-to-r from-red-600 via-red-500
									 to-red-600 hover:bg-gradient-to-br focus:ring-4 focus:outline-none
									  focus:ring-red-300 dark:focus:ring-red-800 shadow-lg shadow-red-500/50 dark:shadow-lg 
									  dark:shadow-red-800/80 font-medium rounded-lg text-sm px-0.5 py-1 text-center me-2 mb-2">VIEW</button>


								</td>
							</tr>
													</tbody>
					</table>
				</div>

				
			</div>
			
		</div>
	);
};

export default Dashboard;
